#!/usr/bin/env bash
# AGENT_BOOTSTRAP_GENERATED
set -euo pipefail

usage() {
  cat <<'HELP'
Usage: scripts/agent-local-only-check.sh status
       scripts/agent-local-only-check.sh pre-push
       scripts/agent-local-only-check.sh scan-ref <commit-ish>

Prevent harness-kit generated files from being pushed. The check fails when a
tracked tree or outgoing push contains agent-bootstrap/harness-kit files that
must remain local-only.
HELP
}

ACTION="${1:-status}"
if [[ "$ACTION" == "-h" || "$ACTION" == "--help" ]]; then
  usage
  exit 0
fi

ROOT_DIR="${AGENT_BOOTSTRAP_ROOT:-$(git rev-parse --show-toplevel)}"
ZERO_SHA="0000000000000000000000000000000000000000"
GITIGNORE_MARKER="# >>> multi-agent bootstrap local state >>>"
VIOLATIONS_FILE=""

cleanup() {
  if [[ -n "${VIOLATIONS_FILE:-}" ]]; then
    rm -f "$VIOLATIONS_FILE"
  fi
}

fail() {
  printf 'agent-local-only-check: ERROR: %s\n' "$*" >&2
  exit 1
}

local_only_reason() {
  local path="$1"
  case "$path" in
    AGENTS.md|AGENTS.md.generated.*|\
    CLAUDE.md|CLAUDE.md.generated.*|\
    GEMINI.md|GEMINI.md.generated.*|\
    .windsurfrules|.windsurfrules.generated.*)
      printf 'agent entrypoint generated by harness-kit\n'
      return 0
      ;;
    .agents/*|.claude/*|.codex/*|.cursor/rules/*|.windsurf/rules/*)
      printf 'agent runtime/config generated by harness-kit\n'
      return 0
      ;;
    docs/agent-configs/*)
      printf 'agent configuration generated by harness-kit\n'
      return 0
      ;;
    docs/superpowers/specs/README.md|\
    docs/superpowers/specs/README.md.generated.*|\
    docs/superpowers/specs/project-tech-stack.md|\
    docs/superpowers/specs/project-tech-stack.md.generated.*|\
    docs/superpowers/specs/project-tech-stack.json|\
    docs/superpowers/specs/project-tech-stack.json.generated.*|\
    docs/superpowers/plans/README.md|\
    docs/superpowers/plans/README.md.generated.*)
      printf 'onboarding scaffold generated by harness-kit\n'
      return 0
      ;;
    scripts/agent-tech-stack-lib.sh|\
    scripts/detect-agent-tech-stack.sh|\
    scripts/agent-hook.sh|\
    scripts/agent-guard.sh|\
    scripts/agent-onboarding.sh|\
    scripts/agent-local-only-check.sh|\
    scripts/verify-ai-deps.sh|\
    scripts/install-git-hooks.sh|\
    scripts/install-rtk.sh|\
    scripts/rtk|\
    scripts/githooks/*)
      printf 'agent runtime script generated by harness-kit\n'
      return 0
      ;;
    .github/workflows/agent-guard.yml|.github/workflows/agent-guard.yml.generated.*)
      printf 'agent guard CI scaffold generated by harness-kit\n'
      return 0
      ;;
    harness-kit/*|.harness-kit/*|agent-bootstrap/*)
      printf 'local harness-kit source/cache copy\n'
      return 0
      ;;
    .gitignore.generated.*)
      printf 'generated .gitignore candidate from harness-kit\n'
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

record_violation() {
  local path="$1"
  local reason="$2"
  local source="$3"
  printf '%s\t%s\t%s\n' "$path" "$reason" "$source" >> "$VIOLATIONS_FILE"
}

check_path() {
  local path="$1"
  local source="$2"
  local reason
  if reason="$(local_only_reason "$path")"; then
    record_violation "$path" "$reason" "$source"
  fi
}

check_gitignore_blob() {
  local source="$1"
  local content="$2"
  if printf '%s\n' "$content" | grep -Fq "$GITIGNORE_MARKER"; then
    record_violation ".gitignore" "contains harness-kit local-only block" "$source"
  fi
}

scan_index() {
  local path
  while IFS= read -r path; do
    [[ -n "$path" ]] || continue
    check_path "$path" "git index"
  done < <(git -C "$ROOT_DIR" ls-files)

  if git -C "$ROOT_DIR" ls-files --error-unmatch .gitignore >/dev/null 2>&1 &&
    [[ -f "$ROOT_DIR/.gitignore" ]]; then
    check_gitignore_blob "working tree" "$(cat "$ROOT_DIR/.gitignore")"
  fi
}

scan_tree() {
  local ref="$1"
  local path content
  while IFS= read -r path; do
    [[ -n "$path" ]] || continue
    check_path "$path" "$ref"
  done < <(git -C "$ROOT_DIR" ls-tree -r --name-only "$ref")

  if git -C "$ROOT_DIR" cat-file -e "$ref:.gitignore" 2>/dev/null; then
    content="$(git -C "$ROOT_DIR" show "$ref:.gitignore")"
    check_gitignore_blob "$ref" "$content"
  fi
}

scan_commit_delta() {
  local commit="$1"
  local path content
  while IFS= read -r path; do
    [[ -n "$path" ]] || continue
    check_path "$path" "$commit"
  done < <(git -C "$ROOT_DIR" diff-tree --root --no-commit-id --name-only -r "$commit")

  if git -C "$ROOT_DIR" diff-tree --root --no-commit-id --name-only -r "$commit" | grep -Fxq ".gitignore" &&
    git -C "$ROOT_DIR" cat-file -e "$commit:.gitignore" 2>/dev/null; then
    content="$(git -C "$ROOT_DIR" show "$commit:.gitignore")"
    check_gitignore_blob "$commit" "$content"
  fi
}

scan_push_update() {
  local local_ref="$1"
  local local_sha="$2"
  local remote_ref="$3"
  local remote_sha="$4"
  local commit commits

  [[ "$local_sha" != "$ZERO_SHA" ]] || return 0
  scan_tree "$local_sha"

  if [[ "$remote_sha" == "$ZERO_SHA" ]]; then
    commits="$(git -C "$ROOT_DIR" rev-list "$local_sha" --not --remotes 2>/dev/null || true)"
    if [[ -z "$commits" ]]; then
      commits="$(git -C "$ROOT_DIR" rev-list -n 1 "$local_sha" 2>/dev/null || true)"
    fi
  else
    commits="$(git -C "$ROOT_DIR" rev-list "$remote_sha..$local_sha" 2>/dev/null || true)"
  fi

  while IFS= read -r commit; do
    [[ -n "$commit" ]] || continue
    scan_commit_delta "$commit"
  done <<< "$commits"
}

run_pre_push() {
  local saw_input=false
  local local_ref local_sha remote_ref remote_sha
  if [[ -t 0 ]]; then
    scan_tree HEAD
    return 0
  fi
  while read -r local_ref local_sha remote_ref remote_sha; do
    saw_input=true
    scan_push_update "$local_ref" "$local_sha" "$remote_ref" "$remote_sha"
  done

  if [[ "$saw_input" != true ]]; then
    scan_tree HEAD
  fi
}

report_and_exit() {
  local count=0
  if [[ ! -s "$VIOLATIONS_FILE" ]]; then
    printf 'agent-local-only-check: ok\n'
    return 0
  fi

  printf 'agent-local-only-check: harness-kit files are local-only and cannot be pushed:\n' >&2
  sort -u "$VIOLATIONS_FILE" | while IFS=$'\t' read -r path reason source; do
    count=$((count + 1))
    if [[ "$count" -le 50 ]]; then
      printf '  - %s (%s; %s)\n' "$path" "$reason" "$source" >&2
    fi
  done
  if [[ "$(sort -u "$VIOLATIONS_FILE" | wc -l | tr -d ' ')" -gt 50 ]]; then
    printf '  ... more paths omitted\n' >&2
  fi
  cat >&2 <<'HELP'

Remove them from Git while keeping local copies, then commit the removal:
  git rm --cached -- <path> [...]

The generated .gitignore block keeps new harness-kit files local after that.
HELP
  return 1
}

main() {
  VIOLATIONS_FILE="$(mktemp)"
  trap cleanup EXIT HUP INT TERM

  case "$ACTION" in
    status)
      scan_index
      ;;
    pre-push)
      run_pre_push
      ;;
    scan-ref)
      [[ -n "${2:-}" ]] || fail "missing ref for scan-ref"
      scan_tree "$2"
      ;;
    *)
      usage >&2
      return 2
      ;;
  esac

  report_and_exit
}

main "$@"
